version: '3.8'

services:
  frontend: 
    image: dmutoni/voting-ms-frontend:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./frontend:/app"
    links:
      - backend
  backend: 
    image: dmutoni/voting-ms-backend:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - "5050:5050"
    expose:
      - "5050"
    build: 
      context: backend
      dockerfile: Dockerfile
  db: 
    image: dmutoni/voting-ms-db:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - "27018:27017"
    expose:
      - "27018"
    build:
      context: .
      dockerfile: db.Dockerfile
# volumes:
#   backend:
#   frontend:
#   db: